import os
import sys
import logging
import struct
import csv
from dataclasses import dataclass
from typing import Tuple, List

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, random_split
from tqdm import tqdm

from NTF import NTF, NTFConfig


@dataclass
class NTFTrainerConfig:
    """Training config for NTF.

    NTF is now trained using CSV-based epsilon data (generated by `Trainer`)
    via `build_ntf_training_data` in NTF.py.
    """

    epochs: int = 50
    batch_size: int = 512
    lr: float = 1e-3
    val_split: float = 0.1
    seed: int = 0
    log_every: int = 50


class QuadNTFDataset(Dataset):
    """Dataset reading per-quad features derived from two CSV files.

    Targets are 2 continuous rate values (inner_rate, outter_rate).
    Both coordinates and epsilon are normalized:
    - Coordinates: normalized to [-1, 1] using global min/max
    - Epsilon: standardized using mean/std computed over the whole dataset
    """

    def __init__(
            self,
            points: np.ndarray,
            quads: np.ndarray,
            inner_rate,
            outter_rate,
            epsilon,
    ):
        super().__init__()
        self.points = points.astype(np.float32)
        self.quads = quads.astype(np.int64)

        Q = self.quads.shape[0]

        def _broadcast_to_array(x, name: str):
            x_arr = np.asarray(x)
            if x_arr.shape == ():
                x_arr = np.full((Q,), x_arr, dtype=np.float32)
            elif x_arr.shape[0] != Q:
                raise ValueError(f"{name} length {x_arr.shape[0]} != num quads {Q}")
            return x_arr.astype(np.float32)

        # 存储 rate 值（浮点数，用于回归）
        self.inner_rate = _broadcast_to_array(inner_rate, "inner_rate")
        self.outter_rate = _broadcast_to_array(outter_rate, "outter_rate")

        # store raw epsilon and compute normalization stats
        self.epsilons_raw = _broadcast_to_array(epsilon, "epsilon")
        self.epsilon_mean = float(self.epsilons_raw.mean())
        self.epsilon_std = float(self.epsilons_raw.std() + 1e-8)
        self.epsilon_min = float(self.epsilons_raw.min())
        self.epsilon_max = float(self.epsilons_raw.max())

        # Coordinate normalization: compute global min/max for all coordinates
        # Normalize to [-1, 1] range
        self.coord_min = self.points.min(axis=0)  # (3,) - min for x, y, z
        self.coord_max = self.points.max(axis=0)  # (3,) - max for x, y, z
        self.coord_center = (self.coord_min + self.coord_max) / 2.0  # (3,)
        self.coord_scale = (self.coord_max - self.coord_min) / 2.0  # (3,)
        # Avoid division by zero for flat dimensions
        self.coord_scale = np.maximum(self.coord_scale, 1e-8)

        if self.quads.ndim != 2 or self.quads.shape[1] != 4:
            raise ValueError(f"quads must have shape (Q,4), got {self.quads.shape}")

        if np.any(self.quads < 0) or np.any(self.quads >= self.points.shape[0]):
            raise ValueError("quad vertex indices out of range for points array")

    def __len__(self) -> int:
        return self.quads.shape[0]

    def __getitem__(self, idx: int):
        v_ids = self.quads[idx]
        verts = self.points[v_ids]  # (4, 3)
        eps_raw = float(self.epsilons_raw[idx])

        # Coordinate normalization: (coord - center) / scale -> [-1, 1]
        verts_norm = (verts - self.coord_center) / self.coord_scale

        # epsilon normalization: standardize using dataset-level mean/std
        eps_norm = (eps_raw - self.epsilon_mean) / self.epsilon_std

        # build input feature: 4*3 normalized coords + 1 normalized epsilon
        geom = verts_norm.astype(np.float32).reshape(-1)
        feat = np.concatenate([geom, np.array([eps_norm], dtype=np.float32)], axis=0)
        x = torch.from_numpy(feat)

        # 2个连续rate值作为目标（inner_rate, outter_rate）
        y = torch.tensor([
            self.inner_rate[idx],
            self.outter_rate[idx],
        ], dtype=torch.float32)

        return x, y


class NTFRegressor(nn.Module):
    """NTF Regressor: outputs 2 continuous rate values (inner_rate, outter_rate).

    Uses regression (MSELoss) instead of classification.
    """

    def __init__(self, in_dim_raw: int, config: NTFConfig) -> None:
        super().__init__()
        self.config = config

        # 使用 NTF 的 encoder
        from NTF import PositionalEncoder
        self.encoder = PositionalEncoder(in_dim=in_dim_raw, levels=config.fflevels)

        # MLP 输出 2 个连续值 (2层隐藏层 + 1层输出层)
        self.net = nn.Sequential(
            nn.Linear(self.encoder.out_dim, config.hidden_dim),
            nn.LeakyReLU(),
            nn.Linear(config.hidden_dim, config.hidden_dim),
            nn.LeakyReLU(),
            nn.Linear(config.hidden_dim, 2),  # 2 rates: inner_rate, outter_rate
        )

        logging.info("Instantiated NTFRegressor with:")
        logging.info(f"  in_dim_raw   = {in_dim_raw}")
        logging.info(f"  enc_out_dim  = {self.encoder.out_dim}")
        logging.info(f"  fflevels     = {config.fflevels}")
        logging.info(f"  hidden_dim   = {config.hidden_dim}")

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Forward pass.

        Args:
            x: tensor of shape (B, in_dim_raw)
        Returns:
            rates: tensor of shape (B, 2) with continuous rate values
                   (inner_rate, outter_rate)
        """
        enc = self.encoder(x)
        return self.net(enc)  # (B, 2)

    def predict_rates(self, x: torch.Tensor) -> torch.Tensor:
        """Return predicted rate values for inner and outter.

        Returns:
            rates: tensor of shape (B, 2) with (inner_rate, outter_rate)
        """
        self.eval()
        with torch.no_grad():
            rates = self.forward(x)  # (B, 2)
        return rates


class NTFTrainer:
    """Trainer using two CSVs -> NTF training data (Regression mode).

    Usage:
      python Trainer.py <points_csv> <quads_csv>

    where:
      - <points_csv> and <quads_csv> are produced by `generate_quad_training_csv`.
    """

    def __init__(self, points_csv: str, quads_csv: str, ntf_config: NTFConfig, trainer_cfg: NTFTrainerConfig):
        self.points_csv = points_csv
        self.quads_csv = quads_csv
        self.ntf_config = ntf_config
        self.config = trainer_cfg

        torch.manual_seed(self.config.seed)
        self.device = 'cuda' if torch.cuda.is_available() else 'cpu'

        # Build arrays directly from two CSVs (points + Pareto quads).
        # points_csv: generated by generate_quad_training_csv, columns: point_id,x,y,z
        # quads_csv:  Pareto/prefix-optimal CSV, columns:
        #   quad_id,v0,v1,v2,v3,epsilon_target,inner_rate,outter_rate

        # Load points
        pts_list = []
        with open(points_csv, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                pts_list.append((float(row["x"]), float(row["y"]), float(row["z"])))
        points = np.array(pts_list, dtype=np.float32)

        # Load quads and per-quad rates/epsilon
        # We also collect quad_id to identify and filter "bad quads"
        raw_data = []  # List of (quad_id, v0, v1, v2, v3, epsilon, inner_rate, outter_rate)

        with open(quads_csv, "r", encoding="utf-8") as f:
            # Peek at first line to determine if CSV has a header
            first_line = f.readline().strip()
            f.seek(0)  # Reset to beginning

            # Check if the first line looks like a header (contains letters)
            # or data (all numeric/comma separated)
            first_fields = first_line.split(',')
            has_header = any(not field.replace('.', '').replace('-', '').replace('e', '').replace('+', '').isdigit()
                             for field in first_fields if field.strip())

            if has_header:
                # Use DictReader for header-based CSV
                reader = csv.DictReader(f)
                # Support both epsilon_target (Pareto CSV) and epsilon (full CSV) column names.
                has_eps_target = "epsilon_target" in (reader.fieldnames or [])
                has_eps = "epsilon" in (reader.fieldnames or [])
                if not (has_eps_target or has_eps):
                    raise KeyError("quads CSV must have either 'epsilon_target' or 'epsilon' column")

                for row in reader:
                    qid = int(row.get("quad_id", 0))
                    v0 = int(row["v0"])
                    v1 = int(row["v1"])
                    v2 = int(row["v2"])
                    v3 = int(row["v3"])

                    ir = float(row["inner_rate"])
                    ot = float(row["outter_rate"])

                    if has_eps_target:
                        eps_val = float(row["epsilon_target"])
                    else:
                        eps_val = float(row["epsilon"])

                    raw_data.append((qid, v0, v1, v2, v3, eps_val, ir, ot))

                logging.info(f"[NTFTrainer] Loaded quads CSV with header: {reader.fieldnames}")
            else:
                # No header: expect columns by index
                # Format: quad_id, v0, v1, v2, v3, epsilon, inner_rate, outter_rate
                reader = csv.reader(f)
                for row in reader:
                    if len(row) < 8:
                        continue  # Skip malformed rows

                    qid = int(row[0])
                    v0 = int(row[1])
                    v1 = int(row[2])
                    v2 = int(row[3])
                    v3 = int(row[4])
                    eps_val = float(row[5])
                    ir = float(row[6])
                    ot = float(row[7])

                    raw_data.append((qid, v0, v1, v2, v3, eps_val, ir, ot))

                logging.info(f"[NTFTrainer] Loaded quads CSV without header (columns by index)")

        logging.info(f"[NTFTrainer] Raw data loaded: {len(raw_data)} samples")

        # ============================================================
        # NOTE: Filtering and augmentation is now handled by DataAugmentor.py
        # The input CSV should already be pre-processed (filtered + augmented)
        # ============================================================

        # Extract arrays from raw_data (no filtering here)
        filtered_data = raw_data
        quads = []
        inner_rate = []
        outter_rate = []
        eps = []

        for row in filtered_data:
            _, v0, v1, v2, v3, eps_val, ir, ot = row
            quads.append((v0, v1, v2, v3))
            eps.append(eps_val)
            inner_rate.append(ir)
            outter_rate.append(ot)

        quads = np.array(quads, dtype=np.int64)
        inner_rate = np.array(inner_rate, dtype=np.float32)
        outter_rate = np.array(outter_rate, dtype=np.float32)
        eps = np.array(eps, dtype=np.float32)

        self.dataset = QuadNTFDataset(
            points=points,
            quads=quads,
            inner_rate=inner_rate,
            outter_rate=outter_rate,
            epsilon=eps
        )

        # save epsilon normalization stats from dataset for later use (e.g., prediction)
        self.epsilon_mean = self.dataset.epsilon_mean
        self.epsilon_std = self.dataset.epsilon_std
        self.epsilon_min = self.dataset.epsilon_min
        self.epsilon_max = self.dataset.epsilon_max

        # save coordinate normalization stats
        self.coord_center = self.dataset.coord_center  # (3,)
        self.coord_scale = self.dataset.coord_scale  # (3,)

        logging.info(f"[NTFTrainer] Coordinate normalization:")
        logging.info(f"  coord_center = {self.coord_center}")
        logging.info(f"  coord_scale  = {self.coord_scale}")

        # Split dataset
        val_len = int(len(self.dataset) * self.config.val_split)
        train_len = len(self.dataset) - val_len
        train_set, val_set = random_split(self.dataset, [train_len, val_len])

        self.train_loader = DataLoader(
            train_set, batch_size=self.config.batch_size, shuffle=True, drop_last=False
        )
        self.val_loader = DataLoader(
            val_set, batch_size=self.config.batch_size, shuffle=False, drop_last=False
        )

        # Raw feature: 4*3 coords + 1 epsilon
        in_dim_raw = 4 * 3 + 1
        self.ntf = NTFRegressor(in_dim_raw=in_dim_raw, config=self.ntf_config).to(self.device)

        # 使用 MSELoss 进行回归
        self.criterion = nn.MSELoss()
        self.optimizer = torch.optim.Adam(self.ntf.parameters(), lr=self.config.lr)

        base, _ = os.path.splitext(self.quads_csv)
        self.model_path = base + '_ntf.pt'

    def run(self) -> None:
        """Main training loop for NTF (regression)."""
        best_val = float('inf')
        global_step = 0

        total_batches = len(self.train_loader) + len(self.val_loader)

        for epoch in range(1, self.config.epochs + 1):
            self.ntf.train()
            running_loss = 0.0

            # 单个 epoch 的进度条，训练+验证共用，覆盖显示
            pbar = tqdm(
                total=total_batches,
                desc=f"Epoch {epoch}/{self.config.epochs}",
                leave=False,
                unit="batch",
                ncols=100,
                file=sys.stdout
            )

            # 训练阶段
            for x, y in self.train_loader:
                x = x.to(self.device)
                y = y.to(self.device)  # (B, 2) 连续rate值

                self.optimizer.zero_grad()
                pred = self.ntf(x)  # (B, 2)

                # MSE损失
                loss = self.criterion(pred, y)

                loss.backward()
                self.optimizer.step()

                running_loss += loss.item() * x.size(0)
                global_step += 1

                pbar.set_postfix(phase="Train", loss=f"{loss.item():.6f}")
                pbar.update(1)

            avg_train = running_loss / max(1, len(self.train_loader.dataset))

            # Validation
            self.ntf.eval()
            val_loss = 0.0
            total = 0
            mae_inner = 0.0
            mae_outter = 0.0

            with torch.no_grad():
                for x, y in self.val_loader:
                    x = x.to(self.device)
                    y = y.to(self.device)

                    pred = self.ntf(x)  # (B, 2)

                    # 计算MSE损失
                    loss = self.criterion(pred, y)
                    val_loss += loss.item() * x.size(0)

                    # 计算MAE
                    mae_inner += torch.abs(pred[:, 0] - y[:, 0]).sum().item()
                    mae_outter += torch.abs(pred[:, 1] - y[:, 1]).sum().item()
                    total += x.size(0)

                    pbar.set_postfix(phase="Val", loss=f"{loss.item():.6f}")
                    pbar.update(1)

            avg_val = val_loss / max(1, len(self.val_loader.dataset))
            avg_mae_inner = mae_inner / max(1, total)
            avg_mae_outter = mae_outter / max(1, total)

            pbar.close()

            # 每个 epoch 结束后，打印一行摘要（覆盖进度条位置）
            print(
                f"\rEpoch {epoch}/{self.config.epochs} | "
                f"train_loss: {avg_train:.6f} | val_loss: {avg_val:.6f} | "
                f"MAE_in: {avg_mae_inner:.3f} | MAE_out: {avg_mae_outter:.3f}",
                end="" if epoch < self.config.epochs else "\n"
            )

            if avg_val < best_val:
                best_val = avg_val
                self._save()

        print()  # 最终换行
        logging.info('[NTF-Trainer] training finished.')
        logging.info(f'[NTF-Trainer] Best model saved (val_loss={best_val:.6f}) -> {self.model_path}')

    def _save(self) -> None:
        torch.save(
            {
                'state_dict': self.ntf.state_dict(),
                'ntf_config': self.ntf_config.__dict__,
                'trainer_config': self.config.__dict__,
                # save epsilon normalization so prediction can reuse it
                'epsilon_mean': self.epsilon_mean,
                'epsilon_std': self.epsilon_std,
                # save epsilon range for clamping during inference
                'epsilon_min': self.epsilon_min,
                'epsilon_max': self.epsilon_max,
                # save coordinate normalization for inference
                'coord_center': self.coord_center.tolist(),  # (3,)
                'coord_scale': self.coord_scale.tolist(),  # (3,)
            },
            self.model_path,
        )

    def load(self) -> None:
        if not os.path.isfile(self.model_path):
            raise FileNotFoundError(self.model_path)
        data = torch.load(self.model_path, map_location=self.device)

        # restore epsilon normalization stats
        self.epsilon_mean = data.get('epsilon_mean', 0.0)
        self.epsilon_std = data.get('epsilon_std', 1.0)

        # re-create NTF with saved config
        ntf_cfg = NTFConfig(**data['ntf_config'])
        self.ntf = NTFRegressor(in_dim_raw=4 * 3 + 1, config=ntf_cfg).to(self.device)
        self.ntf.load_state_dict(data['state_dict'])
        self.ntf.eval()

    def predict(self, quad_vertices: np.ndarray, epsilon: float) -> Tuple[float, float]:
        """Predict inner_rate and outter_rate for a single quad.

        Returns (inner_rate, outter_rate) as float values.
        The caller can round/clamp these as needed.
        """
        if not hasattr(self, 'ntf') or self.ntf is None:
            self.load()

        # apply the same epsilon normalization used during training
        eps_norm = (float(epsilon) - float(self.epsilon_mean)) / float(self.epsilon_std)

        geom = quad_vertices.astype(np.float32).reshape(-1)
        feat = np.concatenate([geom, np.array([eps_norm], dtype=np.float32)], axis=0)
        x = torch.from_numpy(feat).unsqueeze(0).to(self.device)

        with torch.no_grad():
            rates = self.ntf.predict_rates(x)[0]  # (2,)

        return float(rates[0].item()), float(rates[1].item())


def export_ntf_weights(
        model_path: str,
        output_path: str,
        in_dim_raw: int = 13,
) -> None:
    """Export NTF regressor weights to binary file.

    Args:
        model_path: Path to the trained model file (.pt)
        output_path: Path for the output binary file (.ntf)
        in_dim_raw: Raw input dimension (default 13 = 4*3 + 1)
    """

    # ============================================================
    # Export weights to binary file (.ntf) for C++/OpenGL usage
    # ============================================================
    #
    # File format (.ntf) - Regression mode (v2 with coordinate normalization):
    # 1. Header:
    #    - int32: fflevels (Fourier feature levels)
    #    - int32: hidden_dim (hidden layer dimension)
    #    - int32: in_dim_raw (raw input dimension, typically 13: 4*3 coords + 1 epsilon)
    #    - float32: epsilon_mean (epsilon normalization mean)
    #    - float32: epsilon_std (epsilon normalization std)
    #    - float32: epsilon_min (epsilon clamping min)
    #    - float32: epsilon_max (epsilon clamping max)
    #    - float32[3]: coord_center (coordinate normalization center, x/y/z)
    #    - float32[3]: coord_scale (coordinate normalization scale, x/y/z)
    #
    # 2. Network weights (3-layer MLP):
    #    For each layer:
    #    - int32: in_features
    #    - int32: out_features
    #    - float32[out_features * in_features]: weight (row-major)
    #    - float32[out_features]: bias
    # ============================================================

    # Load model
    checkpoint = torch.load(model_path, map_location='cpu')

    # Get config
    ntf_config = NTFConfig(**checkpoint['ntf_config'])
    epsilon_mean = checkpoint.get('epsilon_mean', 0.0)
    epsilon_std = checkpoint.get('epsilon_std', 1.0)
    epsilon_min = checkpoint.get('epsilon_min', 0.0)
    epsilon_max = checkpoint.get('epsilon_max', 1.0)

    # Get coordinate normalization (default to no normalization if not present)
    coord_center = checkpoint.get('coord_center', [0.0, 0.0, 0.0])
    coord_scale = checkpoint.get('coord_scale', [1.0, 1.0, 1.0])

    # Rebuild model and load weights
    model = NTFRegressor(in_dim_raw=in_dim_raw, config=ntf_config)
    model.load_state_dict(checkpoint['state_dict'])
    model.eval()

    logging.info(f"[export_ntf_weights] Loading model: {model_path}")
    logging.info(f"  fflevels     = {ntf_config.fflevels}")
    logging.info(f"  hidden_dim   = {ntf_config.hidden_dim}")
    logging.info(f"  in_dim_raw   = {in_dim_raw}")
    logging.info(f"  epsilon_mean = {epsilon_mean}")
    logging.info(f"  epsilon_std  = {epsilon_std}")
    logging.info(f"  epsilon_min  = {epsilon_min}")
    logging.info(f"  epsilon_max  = {epsilon_max}")
    logging.info(f"  coord_center = {coord_center}")
    logging.info(f"  coord_scale  = {coord_scale}")

    # Extract MLP layer weights
    layers = []
    for module in model.net:
        if isinstance(module, torch.nn.Linear):
            layers.append(module)

    logging.info(f"  Found {len(layers)} linear layers")

    with open(output_path, 'wb') as f:
        # Write header
        f.write(struct.pack('i', ntf_config.fflevels))
        f.write(struct.pack('i', ntf_config.hidden_dim))
        f.write(struct.pack('i', in_dim_raw))
        f.write(struct.pack('f', float(epsilon_mean)))
        f.write(struct.pack('f', float(epsilon_std)))
        f.write(struct.pack('f', float(epsilon_min)))
        f.write(struct.pack('f', float(epsilon_max)))

        # Write coordinate normalization parameters (6 floats)
        for i in range(3):
            f.write(struct.pack('f', float(coord_center[i])))
        for i in range(3):
            f.write(struct.pack('f', float(coord_scale[i])))

        # Write weights for each layer
        for i, layer in enumerate(layers):
            weight = layer.weight.detach().numpy()  # (out_features, in_features)
            bias = layer.bias.detach().numpy()  # (out_features,)

            in_features = weight.shape[1]
            out_features = weight.shape[0]

            logging.info(f"  Layer {i}: ({in_features}, {out_features})")

            f.write(struct.pack('i', in_features))
            f.write(struct.pack('i', out_features))

            # Write weights (row-major, i.e., out_features first)
            weight_flat = weight.flatten().astype(np.float32)
            f.write(weight_flat.tobytes())

            # Write bias
            bias_flat = bias.astype(np.float32)
            f.write(bias_flat.tobytes())

    logging.info(f"[export_ntf_weights] Export completed: {output_path}")

    # Output file size
    file_size = os.path.getsize(output_path)
    logging.info(f"  File size: {file_size} bytes ({file_size / 1024:.2f} KB)")


if __name__ == '__main__':
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s [%(levelname)s] %(message)s',
        handlers=[logging.StreamHandler(sys.stdout)],
    )

    points_csv = "assets/Bayon Lion_baked_points.csv"
    quads_csv = "assets/Bayon Lion_baked_quads_augmented.csv"

    ntf_cfg = NTFConfig(fflevels=2, hidden_dim=16)
    trainer_cfg = NTFTrainerConfig(epochs=20, batch_size=1024, lr=5e-4)

    trainer = NTFTrainer(points_csv, quads_csv, ntf_cfg, trainer_cfg)
    trainer.run()

    # Automatically export weights after training
    ntf_output_path = "assets/Bayon Lion_baked.ntf"
    export_ntf_weights(
        model_path=trainer.model_path,
        output_path=ntf_output_path,
        in_dim_raw=4 * 3 + 1,  # 4 vertices * 3 coords + 1 epsilon
    )

    logging.info(f"[Trainer] Training and export completed!")
    logging.info(f"  PyTorch model: {trainer.model_path}")
    logging.info(f"  Binary weights: {ntf_output_path}")
